# Generated by Django 4.2.7 on 2023-11-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
