# Generated by Django 4.2.7 on 2023-11-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='modified_at',
        ),
    ]
