# Generated by Django 4.2.7 on 2023-11-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_remove_lead_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
