# Generated by Django 4.2.4 on 2023-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_rename_leadfield_leadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Contactado', 'Contactado'), ('Ganador', 'Ganador'), ('Perdedor', 'Perdedor')], default='Nuevo', max_length=10),
        ),
    ]
