# Generated by Django 5.0 on 2023-12-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
